# Site settings
title: Han biog
SEOTitle: 杨翰的博客 | yanghan blog
header-img: img/home-bg.jpg
email: 15894546008@163.com
description: "这里是 @杨翰 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "杨翰, Han杨翰, Han, 杨翰, Hanpro, @Hanpro, 杨翰的博客, Han Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://huangxuan.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: yanghananan
zhihu_username: hanan-49-71
github_username: yanghanGG
douyin_username: yh_ooco7717
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: Han

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true
# whether or not using Sidebar.
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false
# whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
